name: CI

on: [push, pull_request]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3.0.0
        with:
          java-version: 17
          distribution: adopt
          cache: 'gradle'
      - name: Test
        run: ./gradlew clean test
      - name: Publish snapshot to Sonatype
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && github.repository == 'tnlx/jfxoo'
        run: ./gradlew publishToSonatype
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
